version: '3.8'

services:
  #database section
  go-or-cs-identity-db: 
    image: postgres:alpine3.16

  distributed-cache:
    image: redis

  #infrastructure section
  pgadmin:
    image: dpage/pgadmin4

  # portainer:
  #   image: portainer/portainer-ce

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.17.2

  #microservices api section

#network section
networks:
  default:
    name: go_or_cs
    driver: bridge

#volumes section
volumes:
  go_or_cs_identity_data:
    name: identity_data
  go_or_cs_pgadmin_data:
    name: pgadmin_data



