version: '3.8'

services: 
  #go or cs database: postgres
  identity-db:
    container_name: go-or-cs-identity-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=go-or-cs-identity-db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - go_or_cs_identity_data:/var/lib/postgresql/data
    
    #go or cs database: mysql
  
  #infrastructure section
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - "5050:80"
    volumes:
      - go_or_cs_pgadmin_data:/root/.pgadmin